### ISSUE TITLE
Orphaning klr threads

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-node-client#1]
It looks like we're back to orphaning klr threads. I've toggled a couple times and now I have 8 klr threads running. Closing Atom does kill them, but we shouldn't keep adding new klr threads every time we `toggle`.

**Comment by david-driscoll** [comment]
Windows or other?

**Comment by sgwill** [comment]
Sorry, Windows 8.1.

**Comment by david-driscoll** [comment]
Driving me, nuts no idea why it won't die... in a burning ball of fire.

**Comment by sgwill** [comment]
:fire:
