### ISSUE TITLE
npm install doesn't build build-server.sh

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-node-client#262]
I tried the steps of the README to get omnisharp-node-client working on Fedora 24, however the `npm install` didn't generate the `build-server.sh` file to run on Linux.

**Comment by mickaelistria** [comment]
Actually, the issue seems to be that the repo doesn't contain a build-server.sh at all.

**Comment by mickaelistria** [comment]
cannot reproduce this.

**Comment by mjshashank** [comment]
I'm still unable to find/generate the build-server.sh file to run the server on linux. Any leads?
