### ISSUE TITLE
LSP implementation should explicit it supports only "Full" synchronisation.

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-node-client#289]
Currently, Omnisharp node client LSP implementation returns that it support Incremental update ( https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request ServerCapabilities.textDocumentSync ). However, this seems to confuse OmniSharp-node-client in practive. It seems like OmniSharp only support Full synchronisation.

**Comment by mickaelistria** [comment]
I got this issue while working on a client for Language Server. The clients work fine with language servers provided by VSCode (JSON, CSS), but with OmniSharp, when it receives an "Incremental' change, OmniSharp diagnostics suddenly return errors on line that don't exist.
Looking at the errors, I have the impression that the whole document text gets inserted at the document range, rather than the new text as some errors get duplicated with line shift and another one is about a member that cannot use the class name.

**Comment by david-driscoll** [comment]
I need to sit down and do some testing this weekend, when I was working with it last I wasn't seeing any big problems, but that doesn't mean their aren't any.

**Comment by mickaelistria** [comment]
@david-driscoll Did you have the opportunity to look at it? I've got a demo of Eclipse integration with Language Servers in 8 days and would really like to demo OmniSharp, but this issue is a bit annoying as it requires to hack the code for the demo...

**Comment by mickaelistria** [comment]
This issue is a blocker for adoption of OmniSharp in the Eclipse IDE.

**Comment by mickaelistria** [comment]
I'm sorry for my wrong assumptions and for blaming the code too fast. The issue was actually https://bugs.eclipse.org/bugs/show_bug.cgi?id=508873 . Sorry for the noise!

**Comment by david-driscoll** [comment]
👍 rock on.  I'm going to take a day this weekend and work on updating the language support, and hopefully fix the atom integration as well.
