### ISSUE TITLE
Install/Build exit with error

### ISSUE THREAD

**Issue by ReginaldBull** [OmniSharp/omnisharp-node-client#467]
When following the instructions from the readme, I'm getting an error MSBUILD: error MSB1003 indicating there is no project at the folder "\omnisharp-node-client\vendor\src\OmniSharp.TypeScriptGeneration".

Is there something missing to checkout? Or additional steps to perform?

**Comment by felixfbecker** [comment]
This is because the project uses the old project.json format instead of .csproj. Running `dotnet migrate` in vendor/src/OmniSharp.TypeScriptGeneration fixes it.

**Comment by ReginaldBull** [comment]
solved

**Comment by felixfbecker** [comment]
I believe this should be kept open since that migration should be committed. As it stands the project is not compilable out of the box with latest .NET
